# Generated by Django 5.1.6 on 2025-02-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_verified_user_verified_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified_email',
        ),
    ]
